version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  #    extra_requirements:
  #      - docs
  #  - method: pip
  #    path: another/package
  #system_packages: true

sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub
